services:
  car_detection_app:
    build:
      context: .
    container_name: car_detection_app
    image: car_detection_app
    tty: true
    shm_size: "1g"
    volumes:
      - "./CARS/:/opt/app/CARS/"
      - "./configs/:/opt/app/configs/"
      - "./data/:/opt/app/data/"
      - "./configs/clearml.conf:/root/clearml.conf"
    entrypoint: ["/opt/app/entrypoint.sh"]
